package cct.ie.garage.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import cct.ie.garage.entities.Login;
import cct.ie.garage.repositories.LoginRepository;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path = "/garage") // This means URL's start with /demo (after Application path)
//@EnableJpaRepositories("cct.ie.garage.*")
@EntityScan("cct.ie.garage.*")
public class LoginController {
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private LoginRepository loginRepository;

	@PostMapping(path = "/login") // Map ONLY POST Requests
	public @ResponseBody String login(@RequestBody Login login) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

//		Login n = new Login(login.getUsername(), login.getPassword());
		if (loginRepository.auth(login.getUsername(), login.getPassword()) != null) {
			return "Authenticated";
		}
		return "Username or Password incorret. Try again!";

	}

//	@GetMapping(path = "/allVehicles")
//	public @ResponseBody Iterable<Login> getAllVehicles() {
//		// This returns a JSON or XML with the users
//		return loginRepository.findAll();
//	}
}