package cct.ie.garage.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import cct.ie.garage.entities.Customer;
import cct.ie.garage.entities.Staff;
import cct.ie.garage.repositories.StaffRepository;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path = "/garage") // This means URL's start with /demo (after Application path)
//@EnableJpaRepositories("cct.ie.garage.*")
@EntityScan("cct.ie.garage.*")
public class StaffController {
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private StaffRepository staffRepository;

	@PostMapping(path = "/addStaff") // Map ONLY POST Requests
	public @ResponseBody String addCustomer(@RequestBody Staff staff) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Staff n = new Staff(staff.getPpsn(), staff.getName(), staff.getMidName(), staff.getSurname());
		staffRepository.save(n);
		return "Saved";
	}

	@GetMapping(path = "/allStaffs")
	public @ResponseBody Iterable<Staff> getAllStaffs() {
		// This returns a JSON or XML with the users
		return staffRepository.findAll();
	}
}