package cct.ie.garage.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import cct.ie.garage.entities.Stock;
import cct.ie.garage.repositories.StockRepository;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path = "/garage") // This means URL's start with /demo (after Application path)
@EntityScan("cct.ie.garage.*")
public class StockController {
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private StockRepository stockRepository;

	@PostMapping(path = "/addStock") // Map ONLY POST Requests
	public @ResponseBody String addCustomer(@RequestBody Stock stock) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Stock n = new Stock(stock.getName(), stock.getQuantity(), stock.getPrice());
		stockRepository.save(n);
		return "Saved";
	}

	@GetMapping(path = "/allStock")
	public @ResponseBody Iterable<Stock> getAllStock() {
		// This returns a JSON or XML with the users
		return stockRepository.findAll();
	}
}