package cct.ie.garage.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.stereotype.Service;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.ResponseBody;

import cct.ie.garage.entities.Vehicle;
import cct.ie.garage.enums.Fuel;
import cct.ie.garage.repositories.VehicleRepository;

@Service
@Controller // This means that this class is a Controller
public class VehicleController {
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired // This means to get the bean called vehicleRepository
	private VehicleRepository vehicleRepository;

	public VehicleController() {
		
	}
	
	@PostMapping("add") // Map ONLY POST Requests
	public String add(@RequestBody Vehicle vehicle) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		vehicle.setCarLicence("0000");
		vehicle.setFuel(Fuel.DIESEL);
		vehicle.setManufacture("2020");
		vehicle.setId(1);
		vehicleRepository.save(vehicle);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Vehicle> getAllVehicles() {
		// This returns a JSON or XML with the vehicles
		return vehicleRepository.findAll();
	}
}
