package cct.ie.garage.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import cct.ie.garage.entities.Vehicle;
import cct.ie.garage.enums.Fuel;
import cct.ie.garage.repositories.VehicleRepository;

@Controller // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:4200")
@RequestMapping(path = "/garage") // This means URL's start with /demo (after Application path)
@EnableJpaRepositories("cct.ie.garage.*")
@EntityScan("cct.ie.garage.*")
public class VehicleController {
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private VehicleRepository vehicleRepository;

	@PostMapping(path = "/add") // Map ONLY POST Requests
	public @ResponseBody String addVehicle(@RequestBody Vehicle vehicle) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Vehicle n = new Vehicle(vehicle.getMaker(), vehicle.getModel(), Fuel.DIESEL, "00000000", "2020");
		vehicleRepository.save(n);
		return "Saved";
	}

	@GetMapping(path = "/all")
	public @ResponseBody Iterable<Vehicle> getAllVehicles() {
		// This returns a JSON or XML with the users
		return vehicleRepository.findAll();
	}
}